spring:
  datasource:
    url: jdbc:mysql://192.168.25.129:3306/db_user?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 25000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 500000
      pool-name: DatebookHikariCP
      max-lifetime: 28740000
      connection-test-query: SELECT 1
service:
  port: 7070
server:
  port: 9797

