spring:
  datasource:
    url: jdbc:mysql://192.168.25.129:3306/db_user?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 25000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 500000
      pool-name: DatebookHikariCP
      max-lifetime: 28740000
      connection-test-query: SELECT 1
  redis:
    #数据库索引
    database: 0
    host: 192.168.25.129
    port: 6379
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    #连接超时时间
    timeout: 10000

server:
  port: 8988

thrift:
  user:
    ip: user-service
    port: 7070
  message:
    ip: localhost
    port: 9091

